# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1itLjK2C5tfTw0ab0l5B1uW2eMj6dUEyo
"""

Text = ["hello, python is a great language",
        "python is not a good programming language",
        "C++ has been used for years", "I loved that movie [12]" ]


import nltk
import re
sentence_without_expression=[]
for sentence in Text:
    sentence=re.sub('\[[^]]*\]','',sentence)
    sentence = re.sub(r'[^a-zA-Z0-9\s]', '', sentence)
    sentence_without_expression.append(sentence)

print(sentence_without_expression)

from nltk.stem import PorterStemmer

stemming = PorterStemmer()
stemmed_sentence=[]

for sentence in sentence_without_expression:
    sentence= stemming.stem(sentence)
    stemmed_sentence.append(sentence)

print(stemmed_sentence)

from nltk.tokenize import word_tokenize
nltk.download("punkt")


tokenized_word=[]

for sentence in stemmed_sentence:
    word= word_tokenize(sentence)
    tokenized_word.append(word)

print (tokenized_word)

from nltk.corpus import stopwords
nltk.download("stopwords")

stop_words = set(stopwords.words('english'))

sentence_without_stopwords=[]

for sentence in tokenized_word:
    filtered_sentence = [word for word in sentence if word not in stop_words]
    sentence_str = ' '.join(filtered_sentence)
    sentence_without_stopwords.append(sentence_str)

print(sentence_without_stopwords)